Run blink build scripts under Python 3
The scripts in third_party/blink/renderer/build/scripts run on Python 3
on Windows but Python 2 on Linux, which led to a Linux-only presubmit
failure. This standardizes on Python 3. The fix was tested on Linux by
running:

  git cl presubmit --files "third_party/blink/renderer/build/scripts/*"

The failure messages were of this form:
  File ".../make_document_policy_features_tests.py", line 23, in
      test_default_value_control
  ....
  ".../json5_generator.py", line 296, in _write_file_if_changed
      with open(path, "a+", newline='') as output_file:
  TypeError: 'newline' is an invalid keyword argument for this function

and were triggered by crrev.com/c/3657883

The scripts used to run on Python 2 on both Linux and Windows but
crrev.com/c/3646865 switched to Python 3 on Windows without noticing
that Linux was still running on Python 2.

Bug: 1309977, 1313804
Change-Id: I1e13cf6c2781e4f032e32b7d1b8fb66e3bed4290
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3668510
Reviewed-by: Jesse McKenna <jessemckenna@google.com>
Commit-Queue: Jesse McKenna <jessemckenna@google.com>
Auto-Submit: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1007510}
NOKEYCHECK=True
GitOrigin-RevId: 99585a8d84111d0b6c4d8c096df898604bbef86b