ScrollbarsTest: Rename |EventHandler()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    ../../third_party/WebKit/Source/core/layout/ScrollbarsTest.cpp:45:3: error: declaration of ‘blink::EventHandler& blink::{anonymous}::ScrollbarsTest::EventHandler()’ [-fpermissive]
       }
       ^
    In file included from ../../third_party/WebKit/Source/core/layout/ScrollbarsTest.cpp:10:0:
    ../../third_party/WebKit/Source/core/input/EventHandler.h:79:19: error: changes meaning of ‘EventHandler’ from ‘class blink::EventHandler’ [-fpermissive]
     class CORE_EXPORT EventHandler final
                       ^~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having an |EventHandler()| method can change
the meaning of references to |EventHandler| in the code depending on
where it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetEventHandler()|.

Change-Id: Ie2fbab48e3e1f68a80f07d95ccf07bd048df1451
Reviewed-on: https://chromium-review.googlesource.com/968512
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Fredrik Söderquist <fs@opera.com>
Cr-Original-Commit-Position: refs/heads/master@{#544044}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 21860dec29d539508b74ab440ff4e70823134075