Fix ARMEL build failure in blink's WTF code
The commit 5863e513ede6d1f7e9a060f13635fd3916a2183c ("Migrate
WTF::SafeCast to base::checked_cast.") removed the inclusion of
base/numerics/safe_conversions.h from std_lib_extras.h. However,
std_lib_extras.h makes use of intptr_t if ARCH_CPU_ARMEL is defined,
and intptr_t is declared in stdint.h (or cstdint). It's not manually
included anywhere in std_lib_extras.h, and previously stdint.h was only
included indirectly in safe_conversions.h via safe_conversions_impl.h.

With the above change, Debian armhf builds fail with:

In file included from ../../third_party/blink/renderer/platform/cursors.cc:28:
../../third_party/blink/renderer/platform/wtf/std_lib_extras.h:178:29: error: unknown type name 'intptr_t'
  return !(reinterpret_cast<intptr_t>(ptr) % __alignof__(Type));

https://buildd.debian.org/status/fetch.php?pkg=chromium&arch=armhf&ver=105.0.5195.52-1&stamp=1662280031&raw=0
contains the full build log.

This fix changes std_lib_extras.h to explicitly include cstdint.

R=haraken@chromium.org, thakis@chromium.org

Change-Id: I93b06443809f66300b316f404910ffefab08b978
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3872171
Commit-Queue: Nico Weber <thakis@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Andres Salomon <dilinger@queued.net>
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1043186}
NOKEYCHECK=True
GitOrigin-RevId: d48be9327cb317d05d7ca952b23c2839b2dda145