[LayoutNG] Remove/update stale test baselines for multicol.
This baselines must have been created back when we had NG block
fragmentation enabled by default, which apparently generates (or
generated) different paint layer sizes for multicol.

Just removed NG-specific baselines, and the tests pass. With one
exception: fast/forms/select/menulist-appearance-rtl.html still needs an
NG-specific baseline, because RTL text run dumps are prefixed with "RTL"
in legacy, while it's not in NG. Like this:
  text run at (26,0) width 52 RTL: [...]
vs.
  text run at (26,0) width 52: [...]
There are similar differences further below in the file. There are also
some LayoutNGBlockFlow -> LayoutBlockFlow changes under LayoutMenuList,
because we've started to force legacy inside form elements since last
rebaseline.

Bug: 890135
Cq-Include-Trybots: luci.chromium.try:linux_layout_tests_layout_ng
Change-Id: I0da4e267fc216809c54dea0b3f6c7c4b26225a20
Reviewed-on: https://chromium-review.googlesource.com/1250922
Commit-Queue: Koji Ishii <kojii@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#595099}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 734515a070b6d1263e4f72326e64e4e461bcec19