bindings: Import pickle instead of cPickle on Python 3
C:/Program Files/Python38/python.exe ../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py --idl-files-list gen/third_party/blink/renderer/bindings/core/core_global_objects_file_list.tmp gen/third_party/blink/renderer/bindings/core/global_objects_core.pickle
Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 20, in <module>
    from utilities import get_file_contents
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\utilities.py", line 10, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'

Bug: 941669
Change-Id: Ie6615f3a887ebbbc96cc3e507abe814b602f8589
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2125727
Commit-Queue: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754301}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 22401d109e9f0c7f453b5624f51a8286bf56a32f