Make InvalidationType an enum class to clear the blink ns
kInvalidateDescendants was used both in blink/paint and blink/css
and to avoid shadowing, this makes the one in the blink namespace
(InvalidationType::kInvalidateDescendants) into an enum class.

This will make is easier/possible to later turn on the -Wshadow
warning. I'm interested in prohibiting shadowing because I think
it might prevent potential jumbo problems.

The exact warning this avoids is:
In file included from third_party/blink/renderer/core/paint/block_flow_paint_invalidator.cc:5:
third_party/blink/renderer/core/paint/block_flow_paint_invalidator.h:31:5: error: declaration shadows a variable in namespace 'blink' [-Werror,-Wshadow]
    kInvalidateDescendants
    ^
third_party/blink/renderer/core/css/invalidation/invalidation_set.h:52:25: note: previous declaration is here
enum InvalidationType { kInvalidateDescendants, kInvalidateSiblings };
                        ^

Bug: 923510
Change-Id: Ib1ab2720adf1abda4c9ded69d8e086d1e8f3f360
Reviewed-on: https://chromium-review.googlesource.com/c/1483084
Reviewed-by: Anders Hartvoll Ruud <andruud@chromium.org>
Commit-Queue: Daniel Bratell <bratell@opera.com>
Cr-Original-Commit-Position: refs/heads/master@{#635069}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d6d47c80a75b076dfaa20b52ac55057457f252ac