make_runtime_features: Don't import cPickle on Python 3
cPickle has been removed in Python 3.
Import pickle instead, which is functionally equivalent and as performant.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/make_internal_runtime_flags.py", line 34, in <module>
    import make_runtime_features
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\make_runtime_features.py", line 31, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'

Bug: 941669
Change-Id: I8b7c3560c2b20a53a4f69614d9c80dff5cfefe20
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124611
Commit-Queue: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754311}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: db4d850f29a7337ccd9e49bb2351e4154c81b1ac