Remove state variable shadowing in blink/paint
In an effort to reduce or even ban variable shadowing, this renames a
variable. I'm interested in prohibiting shadowing because I think it
might prevent potential jumbo problems.

The exact warning this this avoids is:

third_party/blink/renderer/core/paint/paint_property_tree_builder.cc:1762:40: error: declaration shadows a local variable [-Werror,-Wshadow]

        EffectPaintPropertyNode::State state;
                                       ^
third_party/blink/renderer/core/paint/paint_property_tree_builder.cc:1711:38: note: previous declaration is here
      ScrollPaintPropertyNode::State state;
                                     ^
third_party/blink/renderer/core/paint/paint_property_tree_builder.cc:1776:40: error: declaration shadows a local variable [-Werror,-Wshadow]
        EffectPaintPropertyNode::State state;
                                       ^
third_party/blink/renderer/core/paint/paint_property_tree_builder.cc:1711:38: note: previous declaration is here
      ScrollPaintPropertyNode::State state;
                                     ^

Bug: 923510
Change-Id: Ia64158f91a8f07cd238e01b1e1e31b35a6b5ac06
Reviewed-on: https://chromium-review.googlesource.com/c/1496874
Commit-Queue: Daniel Bratell <bratell@opera.com>
Commit-Queue: Fredrik Söderquist <fs@opera.com>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Fredrik Söderquist <fs@opera.com>
Cr-Original-Commit-Position: refs/heads/master@{#636803}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 1dfdf1b070b0bdeb839714ff9ceea303606b5806