server_process: Access pywin32 exception via pywintypes.error.args.
The migration to Python 3 introduced a regression in
ServerProcess._non_blocking_read_win32() in which a pywintypes.error
thrown via a call to win32pipe.PeekNamedPIpe() could no longer be
accessed as a tuple despite being one:

  Traceback (most recent call last):
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process.py", line 359, in _non_blocking_read_win32
      _, avail, _ = win32pipe.PeekNamedPipe(handle, 0)
  pywintypes.error: (109, 'PeekNamedPipe', 'The pipe has been ended.')

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process_unittest.py", line 115, in test_basic
      line = proc.read_stdout_line(now + 1.0)
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process.py", line 225, in read_stdout_line
      return self._read(deadline, self._pop_stdout_line_if_ready)
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process.py", line 392, in _read
      self._wait_for_data_and_update_buffers_using_win32_apis(
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process.py", line 343, in _wait_for_data_and_update_buffers_using_win32_apis
      output = self._non_blocking_read_win32(out_fh)
    File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\web_tests\port\server_process.py", line 365, in _non_blocking_read_win32
      if error[0] not in (109, errno.ESHUTDOWN):
  TypeError: 'error' object is not subscriptable

This works fine with vpython, but not vpython3. Fix it by making |error|
a pywintypes.error and accessing its |args| attribute as a tuple rather
than the object itself.

Fixed: 1309323
Change-Id: I1a41620f6acf7e37b47e6e18b522930b31566e34
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3571762
Auto-Submit: Raphael Kubo Da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Weizhong Xia <weizhong@google.com>
Commit-Queue: Weizhong Xia <weizhong@google.com>
Cr-Commit-Position: refs/heads/main@{#989008}
NOKEYCHECK=True
GitOrigin-RevId: e313dcd68aa2c657839a289d7c5d861eb50e6a5d