Revert "Roll inspector-protocol to 32cf5f2bf4dc20c73ead291e68d2e2f6b638cd57"
This reverts commit 007a2fa23575a36266ebb25bdcf5b8ee1b1e52d5.

Reason for revert: Seems likely to be the cause of this test failure on linux-bfcache-rel:
https://ci.chromium.org/ui/p/chromium/builders/ci/linux-bfcache-rel/19908/overview
in which the web_test virtual/synchronous_html_parser/http/tests/inspector-protocol/network/request-interception-patterns.js
failed with:
TypeError: Cannot read properties of undefined (reading 'base64Encoded')
    at eval (http://127.0.0.1:8000/inspector-protocol/network/request-interception-patterns.js:57:31)

Original change's description:
> Roll inspector-protocol to 32cf5f2bf4dc20c73ead291e68d2e2f6b638cd57
>
> Includes:
> - https://chromium-review.googlesource.com/c/deps/inspector_protocol/+/3014475
> - https://chromium-review.googlesource.com/c/deps/inspector_protocol/+/3006580
>
> Bug: chromium:1187004, chromium:1187003, chromium:1187006, chromium:1187007
> Change-Id: If3202d9ecbfb88173649502643c7ce0622f4a7f0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3013350
> Commit-Queue: Andrey Kosyakov <caseq@chromium.org>
> Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#900489}

Bug: chromium:1187004, chromium:1187003, chromium:1187006, chromium:1187007
Change-Id: Ic66949959ef5c51728814b1eb1cb284249c0c06a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3021661
Auto-Submit: David Baron <dbaron@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: David Baron <dbaron@chromium.org>
Cr-Commit-Position: refs/heads/master@{#900516}
NOKEYCHECK=True
GitOrigin-RevId: 50def8046725b5b85e32484136d2351553ec0873