bindings: Open pickle file as binary
In Python 3 pickle.dump() writes in binary. Python 2 doesn't care.
Simply open the file as binary, so it works on both.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 109, in <module>
    sys.exit(main())
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 104, in main
    write_pickle_file(output_global_objects_filename,
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\utilities.py", line 358, in write_pickle_file
    pickle.dump(data, pickle_file)
TypeError: write() argument must be str, not bytes

Bug: 941669
Change-Id: I42a1fc355e19e040ea5ee654cf49ab46d11ab769
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2125728
Commit-Queue: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754305}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7a28620f65241ba969e8b39408ce32ea428fda8e