Fix AbortSignal conversion regression
By working around a bug in the IDL compiler when generating RequestInit
with said compiler, a regression was introduced that stopped TypeErrors
from being thrown when RequestInit's signal member does not implement
the AbortSignal interface. This CL fixes that regression and adds tests
for it.

R=kinuko@chromium.org, yoav@yoav.ws

Bug: 836873
Change-Id: I6ab7be2ee8356eb7a997b904d121a7061986096a
Reviewed-on: https://chromium-review.googlesource.com/1123771
Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
Reviewed-by: Adam Rice <ricea@chromium.org>
Commit-Queue: Dominic Farolino <domfarolino@gmail.com>
Cr-Original-Commit-Position: refs/heads/master@{#572449}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 9a63b165102676ece361dd598659551c5b0d0ba4