Android: py2->py3 fix for stack script
From https://chromium-swarm.appspot.com/task?id=5a6626c017af9611:

...
  File "/b/s/w/ir/third_party/android_platform/development/scripts/symbol.py", line 183, in <listcomp>
    _GetApkPackageName(apk_path) == package_name)]
  File "/b/s/w/ir/third_party/android_platform/development/scripts/symbol.py", line 80, in _GetApkPackageName
    aapt_output = subprocess.check_output(
TypeError: a bytes-like object is required, not 'str'

Bug: None
Change-Id: Ia6b8ae3225d0bd9a62dc2d3292a81bc408bf37e4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3601171
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: David Benjamin <davidben@chromium.org>
Commit-Queue: David Benjamin <davidben@chromium.org>
Cr-Commit-Position: refs/heads/main@{#994944}
NOKEYCHECK=True
GitOrigin-RevId: 6cb3b8a17745e5c659a3478f7a1c14bb3d7418bd