Remove variable shadowing in blink/modules/webgl
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The warnings this avoids is:
third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc:3688:18: error: declaration shadows a local variable [-Werror,-Wshadow]
        unsigned length;
                 ^
third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc:3658:13: note: previous declaration is here
    GLsizei length = 0;
            ^
third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc:5234:31: error: declaration shadows a local variable [-Werror,-Wshadow]
      ScopedTexture2DRestorer restorer(gl);
                              ^
third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc:5190:27: note: previous declaration is here
  ScopedTexture2DRestorer restorer(this);

Bug: 923510
Change-Id: Idef0b7f4b47aad7c0199d9e11571dc93d1c94429
Reviewed-on: https://chromium-review.googlesource.com/c/1477679
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#633750}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e692b51de3145467a8a820f8a24c3cbe994475d0