Revert "[Trusted Types] Remove TrustedURL."
This reverts commit 005483fe14c968325e6c8735eb6077049ee997ef.

Reason for revert: <INSERT REASONING HERE>
../../third_party/blink/renderer/core/page/scrolling/text_fragment_anchor_test.cc(8,10): fatal error: 'third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h' file not found
#include "third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h"

Original change's description:
> [Trusted Types] Remove TrustedURL.
> 
> The current Trusted Types spec no longer supports TrustedURL. This CL adapts
> to the spec.
> 
> Bug: 1002555
> Change-Id: I35c6d8a257046558f155b9f38289457b14dcb1d2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1834142
> Commit-Queue: Daniel Vogelheim <vogelheim@chromium.org>
> Reviewed-by: Mike West <mkwst@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#706886}

TBR=vogelheim@chromium.org,mkwst@chromium.org

Change-Id: I9012ad7c3f9f01389ab1aa7a90d5beb7873eab2c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1002555
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1866974
Reviewed-by: Lan Wei <lanwei@chromium.org>
Commit-Queue: Lan Wei <lanwei@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#706979}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a84f1c65c3511283481a5a737a4b51d0abae7a92