GCC: indefinite size LayoutUnit constexpr requires mem-initializer for its property value_
Fix build breakage in GCC, as it requires all the members of a
constexpr constructor to be mem-initialized.

Fixes this build error with GCC:
    ../../third_party/blink/renderer/platform/geometry/layout_unit.h:399:40: error: ‘constexpr blink::LayoutUnit::LayoutUnit(IntegerType) [with IntegerType = int]’ called in a constant expression
      399 | constexpr LayoutUnit kIndefiniteSize(-1);
       |                                        ^
    ../../third_party/blink/renderer/platform/geometry/layout_unit.h:98:22: note: ‘constexpr blink::LayoutUnit::LayoutUnit(IntegerType) [with IntegerType = int]’ is not usable as a ‘constexpr’ function because:
       98 |   constexpr explicit LayoutUnit(IntegerType value) {
          |                      ^~~~~~~~~~
    ../../third_party/blink/renderer/platform/geometry/layout_unit.h:98:22: error: member ‘blink::LayoutUnit::value_’ must be initialized by mem-initializer in ‘constexpr’ constructor
    ../../third_party/blink/renderer/platform/geometry/layout_unit.h:389:7: note: declared here
      389 |   int value_;
          |       ^~~~~~

Bug: 819294
Change-Id: I2699f673f67cda0f9a88f048dd4ff46488e3b184
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3436927
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#967211}
NOKEYCHECK=True
GitOrigin-RevId: 498447ff1d693f878052b6f3082499069fce78cd