Jumbo: Fix a build error in spatial_navigation.h
The build error occurs if using `use_jumbo_build=true` in GN
configuration. It is caused that two files are using the same name for
enum constant. This patch fixes the build error by removing the
RectsAlignment enum definition in spatial_navigation.h.
FYI, the enum is no longer used since https://crrev.com/797463003.

In file included from gen/third_party/blink/renderer/core/unit_tests_jumbo_8.cc:91:
In file included from ./../../third_party/blink/renderer/core/page/spatial_navigation_test.cc:5:
../../third_party/blink/renderer/core/page/spatial_navigation.h:91:23: error: redefinition of enumerator 'kNone'
enum RectsAlignment { kNone = 0, kPartial, kFull };
                      ^
../../third_party/blink/renderer/core/layout/ng/ng_constraint_space.h:40:3: note: previous definition is here
  kNone,     // The node isn't a table cell child.

TBR=bokan@chromium.org

Bug: none
Change-Id: Id43d9992546bb83b6ea1a38f904d2c6fcf44127b
Reviewed-on: https://chromium-review.googlesource.com/1226716
Reviewed-by: Jinho Bang <jinho.bang@samsung.com>
Commit-Queue: Jinho Bang <jinho.bang@samsung.com>
Cr-Original-Commit-Position: refs/heads/master@{#591577}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 81e182051b4dec6f6913d1d2a9db8e1d9362c0c5