Convert FrameMsg_DidSetFramePolicyHeaders to blink.mojom.RemoteFrame
.. interface

As for this old IPC to mojo migration, the CL had to:

1/ moved the dependency management of feature_policy_mojom_traits.cc
  out from the typemap file itself, into the respective GN target,
  otherwise compilation of non-component builds would fail with

  >> ld.lld: error: duplicate symbol:
  >> mojo::StructTraits<
  >>     blink::mojom::ParsedFeaturePolicyDeclarationDataView,
  >>     blink::ParsedFeaturePolicyDeclaration>::Read(
  >>         blink::mojom::ParsedFeaturePolicyDeclarationDataView,
  >>         blink::ParsedFeaturePolicyDeclaration*)

  Similar technique was used in [1].

  [1] https://crrev.com/c/2016524

2/ Temporarily 'undef' STATIC_ASSERT_ENUM definition in
  feature_policy_mojom_traits.h, other otherwise it would fail
  to compile, since it duplicates the same define in wtf/assertions.h.

BUG=1047273
R=dtapuska@chromium.org, haraken@chromium.org, kinuko@chromium.org

Change-Id: I6d0ebb887056af84cddb825096df8cd706dd28d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2050140
Commit-Queue: Antonio Gomes <tonikitoo@igalia.com>
Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#741034}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8851f384ba3b099a2f958fd07f91809ee3546bb6