metrics_proto: Set URL and Short Name in README.chromium
The URL field is not optional in README.chromium, so //tools/licenses.py is
currently failing with

    licenses.LicenseError: couldn't find 'URL' line in README.chromium or licences.py SPECIAL_CASES

in //third_party/metrics_proto.

The actual development repository is not public, and the code in the
Chromium tree acts as the canonical public repository. Add an explanation
instead of a URL in a similar fashion to what is already done in:
* //third_party/bazel/desugar
* //third_party/gvr-android-keyboard
* //third_party/instrumented_libraries
* //third_party/s2cellid

While here, also set a Short Name; even though licenses.py does not
complain, README.chromium.template does not say it is an optional field.

Bug: 805849
Change-Id: I1810e8523a2d3bd210855b2a7c1f997fdb0c7dda
Reviewed-on: https://chromium-review.googlesource.com/960028
Reviewed-by: Steven Holte <holte@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Original-Commit-Position: refs/heads/master@{#542933}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a3db9c7163f755534cf980a81904bec6cef41175