hasher: Alias long for Python 3 compatibility
The L suffix was removed in Python 3. Fortunately this can be simply removed.
The long type was also removed in Python 3, where int does the same thing. Simply alias long to int on Python 3.
Works on both now Python 2 and 3 now, producing the same results as before.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/make_names.py", line 33, in <module>
    import hasher
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\hasher.py", line 26
    return uint32_t(long.__rshift__(self, other) & ((1L << 32) - 1))
                                                      ^
SyntaxError: invalid syntax

Bug: 941669
Change-Id: Ib0369ebce8c3bd843ebbbe24188fbe941fa1a2ad
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2093471
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#748072}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 073c54bd0d3bd4d04f959013b4e31b0e82cb6c67