Remove variable shadowing in blink/frame
In an effort to reduce or even ban variable shadowing, this renames a
couple of variables. I'm interested in prohibiting shadowing because I
think it might prevent potential jumbo problems.

The exact error this avoids is:
third_party/blink/renderer/core/frame/frame_serializer.cc:301:12: error: declaration shadows a local variable [-Werror,-Wshadow]
      KURL url =
           ^
third_party/blink/renderer/core/frame/frame_serializer.cc:261:8: note: previous declaration is here
  KURL url = document.Url();
       ^
third_party/blink/renderer/core/frame/frame_serializer.cc:307:14: error: declaration shadows a local variable [-Werror,-Wshadow]
        KURL url = input->Src();
             ^
third_party/blink/renderer/core/frame/frame_serializer.cc:261:8: note: previous declaration is here
  KURL url = document.Url();
       ^
third_party/blink/renderer/core/frame/frame_serializer.cc:313:14: error: declaration shadows a local variable [-Werror,-Wshadow]
        KURL url =
             ^
third_party/blink/renderer/core/frame/frame_serializer.cc:261:8: note: previous declaration is here
  KURL url = document.Url();
       ^
third_party/blink/renderer/core/frame/local_frame_ukm_aggregator.cc:110:14: error: declaration shadows a local variable [-Werror,-Wshadow]
      String uma_name = uma_percentage_preamble;
             ^
third_party/blink/renderer/core/frame/local_frame_ukm_aggregator.cc:94:10: note: previous declaration is here
    auto uma_name = uma_preamble;
         ^
third_party/blink/renderer/core/frame/rotation_viewport_anchor.cc:52:21: error: declaration shadows a local variable [-Werror,-Wshadow]
    HitTestLocation location(point + point_offset);
                    ^
third_party/blink/renderer/core/frame/rotation_viewport_anchor.cc:30:19: note: previous declaration is here
  HitTestLocation location(point);
                  ^

Bug: 923510
Change-Id: I9bd46559f31e6b3fdb412cf7787b764ae84c775b
Reviewed-on: https://chromium-review.googlesource.com/c/1494659
Commit-Queue: Daniel Bratell <bratell@opera.com>
Commit-Queue: Fredrik Söderquist <fs@opera.com>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Fredrik Söderquist <fs@opera.com>
Cr-Original-Commit-Position: refs/heads/master@{#636453}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7bd45d753f9c8e776b9ef740b7bc8b92a542f681