Revert "OnionSoup: Move web_bluetooth.mojom to public/mojom/bluetooth"
This reverts commit d5b00821af44d875d6cad42ae578b999ddf9316c.

Reason for revert: Breaks compilation.
../../content/public/common/web_preferences.h:18:10: fatal error: 'third_party/blink/public/mojom/v8_cache_options.mojom.h' file not found
#include "third_party/blink/public/mojom/v8_cache_options.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> OnionSoup: Move web_bluetooth.mojom to public/mojom/bluetooth
> 
> This CL moves bluetooth folder from public/platform/modules to
> public/mojom/ to gather mojom files to mojom folder with
> creating web_bluetooth_mojo_bindings.
> 
> Bug: 919393
> Change-Id: I42037e1c9738b03969e927dd00f6b24c2873b364
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1530369
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Reviewed-by: Henrique Nakashima <hnakashima@chromium.org>
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Reviewed-by: Doug Turner <dougt@chromium.org>
> Reviewed-by: Colin Blundell <blundell@chromium.org>
> Commit-Queue: Julie Jeongeun Kim <jkim@igalia.com>
> Cr-Commit-Position: refs/heads/master@{#649061}

TBR=kinuko@chromium.org,blundell@chromium.org,haraken@chromium.org,jbudorick@chromium.org,dougt@chromium.org,hnakashima@chromium.org,jkim@igalia.com

Change-Id: I0ebd0abd67e8ed975cb2f517800296493cdda513
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 919393
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1559180
Reviewed-by: Dominic Battré <battre@chromium.org>
Commit-Queue: Dominic Battré <battre@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#649068}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e1e8c39095a2fd60cb4e28abe219506bd597af84