Use ASSERT_SIZE() to check same sizeof
ASSERT_SIZE() can show the actual sizes when the assert fail, which is
useful to fix failed assert.

Also simplify ASSERT_SIZE() to make the output less verbose. Now the
output is like:
...foo.cc:48:1: error: static_assert failed due to requirement 'WTF::internal::SizesEqual<16, 12>::value' "Foo should stay small"
ASSERT_SIZE(Foo, SameSizeAsFoo);

Change-Id: Ib60951e202006664c13495b668f23fc7ce5fbda6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2290950
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Xianzhu Wang <wangxianzhu@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#787071}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2cde6b4427bf9b7224fddb21c335801e35629d76