Revert "Virtualize TransformStream"
This reverts commit f37fb4118f6220b694609c0208d774707129b95d.

Reason for revert: Broke Fuchsia (at least) compile: https://ci.chromium.org/p/chromium/builders/ci/fuchsia-arm64-cast/25192

In file included from ../../third_party/blink/renderer/core/streams/transform_stream.cc:10:
../../third_party/blink/renderer/core/streams/transform_stream_wrapper.h:9:10: fatal error: 'third_party/blink/renderer/platform/bindings/trace_wrapper_member.h' file not found
#include "third_party/blink/renderer/platform/bindings/trace_wrapper_member.h"

Original change's description:
> Virtualize TransformStream
> 
> Make TransformStream delegate to a new class TransformStreamWrapper for
> the creation of the readable and writable pair. This will allow adding
> in a native implementation in future. TransformStream itself remains a
> concrete class as after the initial creation it has no behaviour
> specific to the underlying implementation.
> 
> Most of the code in transform_stream_wrapper.cc has been moved unchanged
> from transform_stream.cc.
> 
> Rename TransformStreamDefaultController to
> TransformStreamDefaultControllerWrapper and make it inherit from a new
> abstract interface, TransformStreamDefaultControllerInterface. This will
> permit plugging in an alternate implementation.
> 
> Modify TextDecoderStream and TextEncoderStream to use the new interface
> name.
> 
> This is preparation for addition of the new C++ implementation described
> in the design doc:
> 
> https://docs.google.com/document/d/1n0IIRmJb0R-DFc2IhhJfS2-LUwl6iKSBNaR0klr3o40/edit
> 
> BUG=902633
> 
> Change-Id: I5ad376a951dd426e3a8dffbda18643f44dc8daab
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1545952
> Reviewed-by: Joshua Bell <jsbell@chromium.org>
> Reviewed-by: Yutaka Hirano <yhirano@chromium.org>
> Commit-Queue: Adam Rice <ricea@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#647191}

TBR=jsbell@chromium.org,ricea@chromium.org,yhirano@chromium.org

Change-Id: Idb82171e7abe995c6524f11a29181da73c861049
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 902633
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1550319
Reviewed-by: Henrik Grunell <grunell@chromium.org>
Commit-Queue: Henrik Grunell <grunell@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#647192}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f0109f66be57b9194e1d5cb8cd204f61a8aa2428