make_names: Fix dictionary sorting
The make_names.h.tmpl was sorting `entries`, which is a list of dictionaries.
Python 3 doesn't support sorting dictionaries, so this resulted in an error.

I believe trying to sort the dictionaries is actually a bug, as dictionary sorting behaviour is unexpected in Python 2 and is the reason it was removed in Python 3.
This manifests here as the symbols not being sorted alphabetically.
I've added proper sorting by symbol names into make_names.py and removed sorting in the template.
This fixes the incorrect sorting and it not working in Python 3.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/make_names.py", line 117, in <module>
    json5_generator.Maker(MakeNamesWriter).main()
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 339, in main
    writer.write_files(args.output_dir)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 304, in write_files
    self._write_file_if_changed(output_dir, generator(), file_name)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\template_expander.py", line 69, in generator_internal
    return apply_template(
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\template_expander.py", line 62, in apply_template
    return template.render(params)
  File "C:\Google\chromium\src\third_party\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Google\chromium\src\third_party\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Google\chromium\src\third_party\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Google\chromium\src\third_party\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\templates\make_names.h.tmpl", line 22, in <module>
    {% for entry in entries|sort %}
  File "C:\Google\chromium\src\third_party\jinja2\filters.py", line 278, in do_sort
    return sorted(value, key=key_func, reverse=reverse)
TypeError: '<' not supported between instances of 'dict' and 'dict'

Bug: 941669
Change-Id: Id06471635469858a37f6c0d1b3e7abd0f640469e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2125848
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754380}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d8cf0619cf83b3880c2df43b3df9931994615a00