Roll src/third_party/eigen3/src/ 2ce2f5198..011e0db31 (97 commits)
https://chromium.googlesource.com/external/gitlab.com/libeigen/eigen.git/+log/2ce2f5198929..011e0db31d1b

$ git log 2ce2f5198..011e0db31 --date=short --no-merges --format='%ad %ae %s'
2020-10-14 deven.desai.amd Fix for ROCm/HIP breakage - 201013
2020-10-15 rmlarsen Revert change from 4e4d3f32d168ed9ce09d950f099a60ddcd11240f that broke BFloat16.h build with older compilers.
2020-10-15 425418567 Add AVX plog<Packet4d> and AVX512 plog<Packet8d> ops,also unified AVX512 plog<Packet16f> op with generic api
2020-10-13 rmlarsen Add specializations for pmin/pmax with prescribed NaN propagation semantics for SSE/AVX/AVX512.
2020-10-14 rmlarsen Remove leftover debug print statement in cxx11_tensor_expr.cpp
2020-10-14 rmlarsen Revert generic implementation of `predux`, since it break compilation of `predux_any` with MSVC.
2020-10-14 david.tellenbach Add MatrixBase::cwiseArg()
2020-10-13 rmlarsen Get rid of nested template specialization in TensorReductionGpu.h, which was broken by c6953f799b01d36f4236b64f351cc1446e0abe17.
2020-10-13 rmlarsen Add packet generic ops `predux_fmin`, `predux_fmin_nan`, `predux_fmax`, and `predux_fmax_nan` that implement reductions with `PropagateNaN`, and `PropagateNumbers` semantics. Add (slow) generic implementations for most reductions.
2020-10-12 5379597-acxz undefine EIGEN_CONSTEXPR before redefinition
2020-10-10 rmlarsen Make bitwise_helper a device function to unbreak GPU builds.
2020-10-09 rmlarsen Clean up packetmath tests and fix various bugs to make bfloat16 pass (almost) all packetmath tests with SSE, AVX, and AVX512.
2020-10-09 david.tellenbach Disable test exceptions when using OpenMP.
2020-10-09 david.tellenbach Mention problems when using potentially throwing scalars and OpenMP
2020-10-09 quantentortilla Fix typo in Tutorial_BlockOperations_block_assignment.cpp
2020-10-09 david.tellenbach Drop EIGEN_USING_STD_MATH in favour of EIGEN_USING_STD
2020-10-08 rmlarsen Implement generic bitwise logical packet ops that work for all types.
2020-10-08 david.tellenbach Add EIGEN prefix for HAS_LGAMMA_R
2020-10-08 eugene.zhulenev Use lgamma_r if it is available (update check for glibc 2.19+)
2020-10-07 rmlarsen Don't make assumptions about NaN-propagation for pmin/pmax - it various across platforms. Change test to only test for NaN-propagation for pfmin/pfmax.
2020-10-04 david.tellenbach Use reinterpret_cast instead of C-style cast in Inverse_NEON.h
2020-10-02 rmlarsen Don't cast away const in Inverse_NEON.h.
2020-10-02 rmlarsen Use EIGEN_USING_STD to fix CUDA compilation error on BFloat16.h.
2020-10-02 rmlarsen Fix CUDA build breakage and incorrect result for absdiff on HIP with long double arguments.
2020-10-02 janos.meny dont use =* might not return a Scalar
2020-10-01 rmlarsen Fix build breakage with MSVC 2019, which does not support MMX intrinsics for 64 bit builds, see: https://stackoverflow.com/questions/60933486/mmx-intrinsics-like-mm-cvtpd-pi32-not-found-with-msvc-2019-for-64bit-targets-c
2020-10-01 rmlarsen Add a generic packet ops corresponding to {std}::fmin and {std}::fmax. The non-sensical NaN-propagation rules for std::min std::max implemented by pmin and pmax in Eigen is a longstanding source og confusion and bug report. This change is a first step towards addressing it, as discussing in issue #564.
2020-09-30 rmlarsen Specialize pldexp_double and pfdexp_double and get rid of Packet2l definition for SSE. SSE does not support conversion between 64 bit integers and double and the existing implementation of casting between Packet2d and Packer2l results in undefined behavior when casting NaN to int. Since pldexp and pfdexp only manipulate exponent fields that fit in 32 bit, this change provides specializations that use existing instructions _mm_cvtpd_pi32 and _mm_cvtsi32_pd instead.
2020-09-30 cantonios Fix alignedbox 32-bit precision test failure.
2020-09-30 david.tellenbach Fix failure in GEBP kernel when compiling with OpenMP and FMA
2020-09-29 rmlarsen Revert !182.
2020-09-29 rmlarsen Add missing newline at the end of Inverse_NEON.h
2020-09-28 rmlarsen Fix compilation of 64 bit constant arguments to pset1frombits in TypeCasting.h on platforms where uint64_t != unsigned long.
2020-09-28 rmlarsen Fix compilation of pset1frombits calls on iOS.
2020-09-27 chtz Provide a more efficient Packet2l->Packet2d cast method
2020-09-28 peci1 Added AlignedBox::transform(AffineTransform).
2020-09-28 github Make relative path variables of type STRING
2020-09-25 zhuyie Fix Eigen::ThreadPool::CurrentThreadId returning wrong thread id when EIGEN_AVOID_THREAD_LOCAL and NDEBUG are defined
2020-09-22 deven.desai.amd Fix for ROCm/HIP breakage - 200921
2020-09-22 david.tellenbach Add CI configuration for ppc64le
2020-09-21 425418567 Fix the #issue1997 and #issue1991 bug triggered by unsupport a[index](type a: __i28d) ops with MSVC compiler
2020-09-21 david.tellenbach Remove EIGEN_CONSTEXPR from NumTraits<boost::multiprecision::number<...>>
2020-09-19 dev.plvlml Fix using FindStandardMathLibrary.cmake with -Wall (-Wunused-value) added to CMAKE_CXX_FLAG
2020-09-18 rmlarsen Fix breakage in pcast<Packet2l, Packet2d> due to _mm_cvtsi128_si64 not being available on 32 bit x86. If SSE 4.1 is available use the faster _mm_extract_epi64 intrinsic.
2020-09-18 425418567 Fix undefined reference to pset1frombits bug on different platforms
2020-09-18 david.tellenbach Rename variable to avoid shadowing of a previously declared one
2020-09-18 rmlarsen Get rid of initialization logic for blueNorm by making the computed constants static const or constexpr. Move macro definition EIGEN_CONSTEXPR to Core and make all methods in NumTraits constexpr when EIGEN_HASH_CONSTEXPR is 1.
2020-09-18 rmlarsen Fix more mildly embarrassing typos in ARM intrinsics in  PacketMath.h. 'vmvnq_u64' does not exist for some reason.
2020-09-18 rmlarsen Fix typo in PacketMath.h
2020-09-18 rmlarsen Add missing packet op pcmp_lt_or_nan for Packet2d on ARM.
2020-09-17 rmlarsen Disable double version of compute_inverse_size4 on Inverse_NEON.h if Packet2d is not supported.
2020-09-16 brad.king Add support for CastXML on ARM aarch64
2020-09-16 daravi Fix compiler error due to c++20 operator== generation rules
2020-09-15 benoitjacob Remove old Clang compiler bug work-arounds. The two LLVM bugs referenced in the comments here have long been fixed. The workarounds were now detrimental because (1) they prevented using fused mul-add on Clang/ARM32 and (2) the unnecessary 'volatile' in 'asm volatile' prevented legitimate reordering by the compiler.
2020-09-14 timshen Make bfloat16(float(-nan)) produce -nan, not nan.
2020-09-15 425418567 Add plog ops support packet2d for NEON
2020-09-15 rmlarsen Add EIGEN_UNUSED_VARIABLE to unused variable in Memory.h
2020-09-11 pedro.caldeira Fix bfloat16 round on gcc 4.8
2020-09-11 rmlarsen Fix issue #1968. Don't discard return value from "new" in C++17.
2020-09-12 425418567 Unified sse pldexp_double api
2020-09-12 rmlarsen Make blueNorm threadsafe if C++11 atomics are available.
2020-09-11 david.tellenbach New CI infrastructure, including AArch64 runners
2020-09-10 N.Dekker Fix half_impl::float_to_half_rtne(float) warning: '<<' causes overflow
2020-08-21 pedro.caldeira Add missing functions for Packet8bf in Altivec architecture. Including new tests for bfloat16 Packets. Fix prsqrt on GenericPacketMath.
2020-09-08 425418567 Add Neon psqrt<Packet2d> and pexp<Packet2d>
2020-09-07 Alexander.Neumann remove semi triggering -Wextra-semi-stmt
2020-09-04 zhengrg3 Add Inverse_NEON.h
2020-05-20 everton.constantino MatrixProuct enhancements:
2020-09-01 everton.constantino Changing u/int8_t to un/signed char because clang does not understand it.
2020-09-02 g.gael fix #1901: warning in Mode==(Upper|Lower)
2020-08-28 hans-johnson BUG: cmake_minimum_required must be the first command
2020-08-28 chip.kerchner Change Packet8s and Packet8us to use vector commands on Power for pmadd, pmul and psub.
2020-08-26 g.gael Fix #1974: assertion when reserving an empty sparse matrix
2020-08-21 425418567 add psqrt ops support packet2f/packet4f for NEON
2020-08-20 georg.jaeger adding attributes to constructors to support hip-clang on ROCm 3.5
2020-08-19 deven.desai.amd Fixing a CUDA / P100 regression introduced by PR 181
2020-08-19 david.tellenbach Fix nightly CI configuration
2020-08-19 david.tellenbach Add possibility to split test suit build targets and improved CI configuration
2020-08-14 rmlarsen Add missing inline keyword in Quaternion.h.
2020-08-14 david.tellenbach Disable min/max NaN propagation in test cxx11_tensor_expr
2020-08-14 david.tellenbach Fix compilation error in blasutil test
2020-08-14 david.tellenbach Replace the call to int64_t in the blasutil test by explicit types
2020-08-13 david.tellenbach bfloat16 packetmath for Arm Neon backend
2020-06-24 pedro.caldeira Add support for Bfloat16 to use vector instructions on Altivec architecture
2020-08-05 deven.desai.amd Adding an explicit launch_bounds(1024) attribute for GPU kernels.
2020-08-04 zach.garrett Temporarily turn off the NEON implementation of pfloor as it does not work for large values.
2020-08-03 david.tellenbach Disable CI buildstage again
2020-07-29 g.gael add a banner to advertise the survey
2020-07-28 david.tellenbach Fix StlDeque for GCC 10
2020-07-25 teng.lu Fix undefine BF16 union behavior in AVX512.
2020-07-28 rmlarsen Inherit alignment trait from argument in TensorBroadcasting to avoid segfault when the argument is unaligned.
2020-07-27 david.tellenbach Fix clang-tidy warnings in generic bfloat16 implementation
2020-07-25 46016483+qxxxb Fix CMake install command
2020-07-24 david.tellenbach Don't allow failure for CI build stage anymore
2020-07-24 david.tellenbach Improve CI configuration
2020-07-24 g.gael Add missing footer declaration
2020-07-23 david.tellenbach Fix bfloat16 casts

Created with:
  roll-dep src/third_party/eigen3/src

Change-Id: Idad1c054d7992062c2f4068204fd692da11c9ebf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2694058
Reviewed-by: Sophie Chang <sophiechang@chromium.org>
Commit-Queue: Michael Crouse <mcrouse@chromium.org>
Cr-Commit-Position: refs/heads/master@{#854111}
GitOrigin-RevId: 4bb0367a2e1872b54524cecc8aebc6dc5533433c