Remove variable shadowing in blink/modules/webaudio
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The exact error this avoids is:
third_party/blink/renderer/modules/webaudio/audio_worklet_global_scope.cc:347:17: error: declaration shadows a local variable [-Werror,-Wshadow]
  for (uint32_t output_bus_index = 0; output_bus_index < output_buses->size();
                ^
third_party/blink/renderer/modules/webaudio/audio_worklet_global_scope.cc:253:12: note: previous declaration is here
  uint32_t output_bus_index = 0;
           ^
1 error generated.

Bug: 923510
Change-Id: Ic861379f7892eb044b4ab3035bde2271521fd2c1
Reviewed-on: https://chromium-review.googlesource.com/c/1477011
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#633129}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 1895a5701ffa2639f075a58278c7a65f4849677b