Remove variable shadowing in blink/modules/notifications
In an effort to reduce or even ban variable shadowing, this renames
a variable to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The exact error this avoids is:
third_party/blink/renderer/modules/notifications/notification_data.cc:93:45: error: declaration shadows a local variable [-Werror,-Wshadow]

    SerializedScriptValue::SerializeOptions options;
                                            ^
./../../third_party/blink/renderer/modules/notifications/notification_data.cc:43:32: note: previous declaration is here
    const NotificationOptions* options,
                               ^

Bug: 923510
Change-Id: Ie49096ef30fbab30567ad45f3f2d8b76a8eab9ed
Reviewed-on: https://chromium-review.googlesource.com/c/1478891
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Daniel Bratell <bratell@opera.com>
Cr-Original-Commit-Position: refs/heads/master@{#633744}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b969b739bc98312834daa07785cb8e18ccc4bcfc