Fix wptserve.py when log files can't be removed.
Fixes a logic issue that cause the wptserve script to hang
indefinitely when the WPT Log file cannot be removed.
Also causes the underlying exception to be printed to
the screen.

vpython3 third_party\blink\tools\run_blink_wptserve.py -t Default
Generated content (out/<build directory>/gen) is served from out/Release/gen by default. Specify an alternate directory with '-t <build directory>'.
Failed to remove old wptserve wptserve_stderr files
Traceback (most recent call last):
  File "C:\Users\suyash\OneDrive\Desktop\chromium\src\third_party\blink\tools\blinkpy\web_tests\servers\server_base.py", line 212, in _remove_stale_logs
    self._remove_log_files(self._output_dir, log_prefix)
  File "C:\Users\suyash\OneDrive\Desktop\chromium\src\third_party\blink\tools\blinkpy\web_tests\servers\server_base.py", line 256, in _remove_log_files
    self._filesystem.remove(full_path)
  File "C:\Users\suyash\OneDrive\Desktop\chromium\src\third_party\blink\tools\blinkpy\common\system\filesystem.py", line 332, in remove
    osremove(self._path_for_access(path))

Example:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\suyas\\OneDrive\\Desktop\\chromium\\src\\out\\Default\\layout-test-results\\wptserve_stderr.txt'
Bug: None
Change-Id: Ib5d97292c37c226da8341dd066b3d66fa2e6e99b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3812487
Reviewed-by: Rakib Hasan <rmhasan@google.com>
Commit-Queue: Suyash Nayan <suyashnyn1@gmail.com>
Cr-Commit-Position: refs/heads/main@{#1032653}
NOKEYCHECK=True
GitOrigin-RevId: 8fea8ba7b6ddefbba2c320916b95d456dc5cae15