web_idl: Don't import exceptions
The exceptions module has been removed in Python 3.
Instead use them from the global namespace, which works on both.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/collect_idl_files.py", line 16, in <module>
    import web_idl
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\web_idl\__init__.py", line 39, in <module>
    from .attribute import Attribute
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\web_idl\attribute.py", line 15, in <module>
    from .idl_type import IdlType
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\web_idl\idl_type.py", line 5, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'

Bug: 941669
Change-Id: I5744867f51e522b532aef3b82b0a38b1188ee16c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124830
Commit-Queue: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754310}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8d7b3908d4d898d2b0c6e542f1c2d4e1710bd189