bindings: Load pickled files as binary
Pickled data is binary, so we need to open it as binary when loading it.
This fixes loading on Python 3.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_global_constructors.py", line 214, in <module>
    sys.exit(main())
  File "../../third_party/blink/renderer/bindings/scripts/generate_global_constructors.py", line 190, in main
    read_pickle_file(options.global_objects_file))
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\utilities.py", line 328, in read_pickle_file
    return pickle.load(pickle_file)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

Bug: 941669
Change-Id: I471be513650f7d6aada4ef1dbb8d08f6223091ac
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124498
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
Reviewed-by: Kenichi Ishibashi <bashi@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754377}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 9e3bed423b1df958aeab6a9234fe42bbdbe64d1c