mediapipe: add include and update visibility
registration.h uses macros such as CHECK_*, so it needs to
include absl's check. Without this errors such as the following are
generated:

In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/node.h:8:
In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/contract.h:10:
In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/packet.h:18:
In file included from ../../third_party/mediapipe/src/mediapipe/framework/packet.h:30:
../../third_party/mediapipe/src/mediapipe/framework/deps/registration.h:274:7: error: use of undeclared identifier 'CHECK_EQ'
  274 |       CHECK_EQ(1u, names.size())

This also adds absl's log/check to a bunch of places that needed.

Bug: None
Change-Id: I7c0b19614ab4c1b3ab25c173390c8c2234b28bb1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4697420
Reviewed-by: Rick Byers <rbyers@chromium.org>
Commit-Queue: Scott Violet <sky@chromium.org>
Reviewed-by: Robert Ogden <robertogden@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1171991}
NOKEYCHECK=True
GitOrigin-RevId: 47515dddcc8f09e62d1b169d1ae74de36a910009