WebInputEvent: Include <memory> for std::unique_ptr.
IWYU. This also fixes the libstdc++ build after commit ba38c72a2 ("Modernize
WebInputEvent"):

    ../../third_party/blink/public/common/input/web_input_event.h:435:16: error: no template named 'unique_ptr' in namespace 'std'
      virtual std::unique_ptr<WebInputEvent> Clone() const = 0;
              ~~~~~^

Bug: 957519
Change-Id: I9f72c49a0b8f551adc784e81e944176170094c4a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1989538
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#730525}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d8f1722504773efb56646ed9e8e57cac89dae17f