Using device serial when using adb.
The Android device serial number, specified by the --device-serial
command-line option, was unused by the android_webview wptrunner.
This resulted in adb failing with the following error:

    adb wait-for-device
    error: more than one device/emulator

Bug: None
Change-Id: I85e236297d7e83950ac26a9283bdad4ef642d62c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1845486
Commit-Queue: Chris Mumford <cmumford@google.com>
Reviewed-by: Robert Ma <robertma@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#704747}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8690a726cc7668ef9460176753bf007c4c26d365