Include filename in IDL assertion error messages
This script runs on multiple input files provided in --idl-files-list,
so an assertion error causes a generic build failure without any clear
indication which of the inputs was problematic.

This change adds the filename and additional context to the assertion
error messages.

Before/after example:

  File "../../third_party/blink/renderer/bindings/scripts/generate_origin_trial_features.py", line 72, in read_idl_file
    assert len(interfaces) == 1
AssertionError

AssertionError: Expected one interface in file '../../third_party/blink/renderer/modules/example_init.idl', found 0
Change-Id: I5de2abbec9b38a72b19b7c1598654d11ab006767
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2261266
Commit-Queue: Klaus Weidner <klausw@chromium.org>
Reviewed-by: Hitoshi Yoshida <peria@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#782584}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 260e63703c266e175a597c0617efabd6e3f99426