Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true
Stacks that appear in logcats draw attention and often get blamed as the
cause for failing tests.

This one looks like:

java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
  at ...

Bug: 1334374
Change-Id: Ia7dd1eccf5edd923380bd3405d914174d2254239
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3935167
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Benjamin Joyce (Ben) <bjoyce@chromium.org>
Commit-Queue: Benjamin Joyce (Ben) <bjoyce@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1084407}
NOKEYCHECK=True
GitOrigin-RevId: 1e0efe2a67cd48156a617e61559e2dd675813d95