libstdc++: explicitly declare default constructor of WTF::DequeIterator
Using std::minmax_element on a WTF::Deque iterator with libstdc++ from
GCC 5+ fails to compile:
/usr/include/c++/9/bits/stl_algo.h:3334:24: error: no matching function for call to ‘WTF::DequeIterator<int, 0, WTF::PartitionAllocator>::DequeIterator(<brace-enclosed initializer list>)’
 3334 |       _ForwardIterator __min{}, __max{};

This is because it will try to create an iterator of the DequeIterator
type with no parameters (or with an empty list of initializers), but
that constructor is not available. So this changeset adds it.

Bug: 957519

Change-Id: I95e54a2fd95b19c0d439e9067105b7e388bdea61
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2051932
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Original-Commit-Position: refs/heads/master@{#740842}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a089aa8aafa2cabc331df6ea450fb75b77e75ff7