gperf: Use __name__ instead of func_name
func_name has been removed in Python 3.
__name__ does the same thing and exists in both Python 2 and 3.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/core/css/parser/make_atrule_names.py", line 11, in <module>
    class AtRuleNamesWriter(json5_generator.Writer):
  File "../../third_party/blink/renderer/build/scripts/core/css/parser/make_atrule_names.py", line 53, in AtRuleNamesWriter
    def generate_implementation(self):
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\gperf.py", line 74, in wrapper
    generator_internal.func_name = generator.func_name
AttributeError: 'function' object has no attribute 'func_name'

Bug: 941669
Change-Id: I8eac2f3e67c235bb0cad5520c71916aa5f6fd13a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124613
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754405}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 89c3c72494f3cf3f3e079030fc1f43a9bd5adf99