Revert "Soft navigation popstate: Fix a typo and add clarifying dchecks"
This reverts commit 4e343b2d54b03fb7633f25306368cdc4bd28253c.

Reason for revert: Compile failure on Win x64 builder:

error: no member named 'soft_navigation_heuristics_task_id' in 'blink::mojom::CommitNavigationParams'

https://ci.chromium.org/ui/p/chromium/builders/ci/Win%20x64%20Builder%20(dbg)/149939/overview

Original change's description:
> Soft navigation popstate: Fix a typo and add clarifying dchecks
>
> This CL fixes a typo, where some of the instances of
> `soft_navigation_heuristics_task_id` were missing an "s", making it hard
> to search for the whole flow.
> It also expands an existing DCHECK, to make its cause clearer when it
> is being hit in Canary.
>
> Bug: 1403900
> Change-Id: Ifdce1cc2882e647a9549c155f08e346e847c401f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4154992
> Reviewed-by: Nasko Oskov <nasko@chromium.org>
> Commit-Queue: Yoav Weiss <yoavweiss@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1091354}

Bug: 1403900
Change-Id: Ic5d0ea0a64fd0aeea603e61dc1076cea57416a8d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4156733
Reviewed-by: Victor Tan <victortan@chromium.org>
Owners-Override: Matt Jones <mdjones@google.com>
Commit-Queue: Victor Tan <victortan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1091374}
NOKEYCHECK=True
GitOrigin-RevId: bab54dc00fe4f9bd7ca43d72274a7a4f7359131f