Roll nearby-connections from ea3fa0e3924c to 43ec97b13bda (16 revisions)
https://chromium.googlesource.com/external/github.com/google/nearby-connections.git/+log/ea3fa0e3924c..43ec97b13bda

2023-01-20 awadhera@google.com Add missing die_if_null.h include
> PiperOrigin-RevId: 503504149
>

2023-01-20 bourdakos@google.com Internal change
> PiperOrigin-RevId: 503320554
>

2023-01-20 guogang@google.com list IP addresses in priority
> PiperOrigin-RevId: 503310798
>

2023-01-20 bourdakos@google.com Refactor nearby connections clients to be organized by languages.
> PiperOrigin-RevId: 503308736
>

2023-01-19 eidenkim@google.com Fix folder transfer with non-English folders.
> PiperOrigin-RevId: 503235989
>

2023-01-19 hais@google.com Adding Anti Spoofing Key Pair into Device in proto.
> PiperOrigin-RevId: 503214302
>

2023-01-19 guogang@google.com Fixed the crash when checking IP addresses
> PiperOrigin-RevId: 503048520
>

2023-01-18 jsobczak@google.com Migrate to absl::AnyInvocable in NP.
> Replaces a bunch of std::function uses with absl::AnyInvocable.
>
> PiperOrigin-RevId: 502960326
>

2023-01-18 hais@google.com Remove PayLoad::AsBytes()&& to fix -Wreturn-stack-address error
> With never versions of libc++, Chromium builds would fail with:
>
>   ../../third_party/nearby/src/connections/payload.cc:105:50:
>   error: returning reference to local temporary object [-Werror,-Wreturn-stack-address]
>       return result ? std::move(*result) : std::move(ByteArray());
>                                                      ^~~~~~~~~~~
>
> Before this libc++ version, the error was masked by the std::move.
>
> If I understand correctly, the only user of this function was
> BytesInternalPayload::DetachNextChunk() which was going to make a copy of the
> ByteArray annyways, so it might as well use the AsBytes() overload that returns
> a const ref.
>
> See also https://crbug.com/1407615#c2
>
> PiperOrigin-RevId: 502946204
>

2023-01-18 qinwangz@google.com Refactor Crypto  Library
> PiperOrigin-RevId: 502942033
>

2023-01-18 eidenkim@google.com Update custom path log to show correct path
> PiperOrigin-RevId: 502765322
>

2023-01-18 eidenkim@google.com Update custom path log to show correct path
> PiperOrigin-RevId: 502735941
>

2023-01-18 qinwangz@google.com Migrate TaskRunner from location/nearby to third_party/nearby
> PiperOrigin-RevId: 502733409
>

2023-01-17 guogang@google.com Enable connection timeout feature
> PiperOrigin-RevId: 502701814
>

2023-01-17 jsobczak@google.com Subscribe for public credentials update
> Nearby Presence scanning sessions may be very long. We need a way to notify the scanner that new credentials were added during scanning.
> `SubscribeForPublicCredentials()` allows us to subscribe for such updates.
>
> PiperOrigin-RevId: 502699345
>

2023-01-17 guogang@google.com Reduce IP check interval and put more logs for Wi-Fi hotspot
> PiperOrigin-RevId: 502698293
>

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://skia-autoroll.corp.goog/r/nearby-connections-chromium
Please CC chromeos-cross-device-eng+autoroll@google.com,jonfan@google.com,nearby-chromeos-eng+autoroll@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Cq-Include-Trybots: luci.chrome.try:linux-nearby-chrome-fyi
Bug: None
Test: autoroller
Change-Id: Ic10288e95ff7180bb5507ce2f77792279f77d632
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4182941
Commit-Queue: Anay Wadhera <awadhera@google.com>
Reviewed-by: Crisrael Lucero <crisrael@google.com>
Cr-Commit-Position: refs/heads/main@{#1095314}
NOKEYCHECK=True
GitOrigin-RevId: e7c91b3eace071cb24bcf6ac00c32e5ca4001a9e