NGFragmentItemsBuilder: Call std::unique_ptr::get() in DCHECK.
Follow-up to commit 50c8bd960 ("Make AssociateNextForSameLayoutObject() not
to hit DCHECK for list marker"), which has a call that looks like

    DCHECK(...) << foo;

where |foo| is a std::unique_ptr fails with libstdc++ because there is no
operator<< overload for std::unique_ptr until C++20 (libc++ just happens to
have it):

    ../../third_party/blink/renderer/core/layout/ng/inline/ng_fragment_items_builder.cc:204:56: error: invalid operands to binary expression ('std::basic_ostream<char, std::char_traits<char> >::__ostream_type' (aka 'basic_ostream<char, std::char_traits<char> >') and 'std::unique_ptr<blink::NGFragmentItem, std::default_delete<blink::NGFragmentItem> >')
      DCHECK(items_.IsEmpty() || items_[0]->IsContainer()) << items_[0];
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~

Bug: 957519, 980914
Change-Id: Id9ae7ecf1bcb871c47127816703cf135630808a0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1950985
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Koji Ishii <kojii@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#721931}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 01e5743812cfeeabc50c4d03e7876854fadabd37