Run check_blink_style.py under Python 3
check_blink_style.py was still running under Python 2 so I changed its
invocation from python_executable to python3_executable. This then hit
this error:

    File "...\tools\check_blink_style.py", line 44, in <module>
      sys.exit(CheckBlinkStyle().main())
    File "...\tools\blinkpy\style\main.py", line 157, in main
      patch_checker.check(patch)
    File "...\tools\blinkpy\style\patchreader.py", line 51, in check
      patch_files = DiffParser(patch_string.splitlines()).files
    File "...\tools\blinkpy\common\checkout\diff_parser.py", line 90, in __init__
      self.files = self._parse_into_diff_files(diff_input)
    File "...\tools\blinkpy\common\checkout\diff_parser.py", line 100, in _parse_into_diff_files
      line = line.rstrip('\n')
  TypeError: a bytes-like object is required, not 'str'

I was confused at first, but rstrip() can be called on bytes or on an
str and it expects its parameter to match. I fixed that by decoding from
bytes to str earlier in the call stack.

Because _checkStyle is only called on upload presubmits I used this
command for testing:

  git cl presubmit --force --files third_party/blink/PRESUBMIT.py --upload

Once I'd created the fix I did broader testing with this command:

  git cl presubmit --files third_party/blink/* --force --upload

and realized that the command lines on Windows were too long, so I
lowered the files_per_command value on Windows from 70 to 40. Passing a
list of files in a file would be better, but this will do for now.

Bug: 1313804
Change-Id: Ief4569759e8d782e3c9c631492c59e9812e2116c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3722336
Reviewed-by: Kent Tamura <tkent@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1017379}
NOKEYCHECK=True
GitOrigin-RevId: 5130baf6222640f259aa46417b889359961d1225