WebFrameTest: Rename |LocalFrameView()| to avoid naming conflicts
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    ../../third_party/WebKit/Source/core/exported/WebFrameTest.cpp: At global scope:
    ../../third_party/WebKit/Source/core/exported/WebFrameTest.cpp:12592:3: error: declaration of ‘blink::LocalFrameView* blink::SlimmingPaintWebFrameTest::LocalFrameView()’ [-fpermissive]
       }
       ^
    In file included from ../../third_party/WebKit/Source/core/frame/LocalFrame.h:41:0,
                     from ../../third_party/WebKit/Source/core/page/Page.h:33,
                     from ../../third_party/WebKit/Source/core/page/PageVisibilityObserver.h:31,
                     from ../../third_party/WebKit/Source/core/html/canvas/HTMLCanvasElement.h:44,
                     from ../../third_party/WebKit/Source/core/html/canvas/CanvasRenderingContext.h:32,
                     from ../../third_party/WebKit/Source/core/html/canvas/ImageData.h:34,
                     from ../../third_party/WebKit/Source/bindings/core/v8/serialization/SerializedColorParams.h:8,
                     from ../../third_party/WebKit/Source/bindings/core/v8/serialization/V8ScriptValueSerializer.h:11,
                    from ../../third_party/WebKit/Source/core/exported/WebFrameTest.cpp:45:
    ../../third_party/WebKit/Source/core/frame/LocalFrameView.h:105:19: error: changes meaning of ‘LocalFrameView’ from ‘class blink::LocalFrameView’ [-fpermissive]
     class CORE_EXPORT LocalFrameView final
                       ^~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |LocalFrameView()| method can change
the meaning of references to |LocalFrameView| in the code dependending on
where it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetLocalFrameView()|.

Change-Id: I3aa9502080708653bdff68eaec51fe61850b4877
Reviewed-on: https://chromium-review.googlesource.com/968424
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Original-Commit-Position: refs/heads/master@{#544028}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b032279bc4fdce5a77a360206041fbb28b6fa223