Receive subprocess output & open file in text mode
Fix the following two python errors when running generate_configs.py and
generate_source.py, respecticely. These errors started to appear on
March 1st or 2nd because I ran the scripts successfully on Feb. 28th.
The errors are related to comparisons between bytes and str objects. It
seems that implicit conversions between str and bytes are now disabled.

  Traceback (most recent call last):
    File "chromium/src/third_party/dav1d/./generate_configs.py", line 228, in <module>
      main()
    File "chromium/src/third_party/dav1d/./generate_configs.py", line 209, in main
      win_x86_env = SetupWindowsCrossCompileToolchain('x86')
    File "chromium/src/third_party/dav1d/./generate_configs.py", line 59, in SetupWindowsCrossCompileToolchain
      win_dirs = gn_helpers.FromGNArgs(output)
    File "chromium/src/build/gn_helpers.py", line 219, in FromGNArgs
      return parser.ParseArgs()
    File "chromium/src/build/gn_helpers.py", line 351, in ParseArgs
      self.ReplaceImports()
    File "chromium/src/build/gn_helpers.py", line 279, in ReplaceImports
      if not any(line.startswith('import(') for line in lines):
    File "chromium/src/build/gn_helpers.py", line 279, in <genexpr>
      if not any(line.startswith('import(') for line in lines):
  TypeError: startswith first arg must be bytes or a tuple of bytes, not str

  Traceback (most recent call last):
    File "chromium/src/third_party/dav1d/./generate_source.py", line 80, in <module>
      main()
    File "chromium/src/third_party/dav1d/./generate_source.py", line 76, in main
      _WriteGn(fd)
    File "chromium/src/third_party/dav1d/./generate_source.py", line 51, in _WriteGn
      fd.write(_COPYRIGHT)

  TypeError: a bytes-like object is required, not 'str'

Change-Id: If32a69d105a7d068af2d95fbfcfeed3db9485ffe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3501415
Reviewed-by: Dan Sanders <sandersd@chromium.org>
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
Commit-Queue: Wan-Teh Chang <wtc@google.com>
Cr-Commit-Position: refs/heads/main@{#977283}
NOKEYCHECK=True
GitOrigin-RevId: ee7d6591382819141e21f1d85de3ca42d134512e