remove mac12 builder
Right now mac12 builder is only a CI builder, but not a try builder.
We should remove it from builders.json until we add it as a try
builder as the importer fails due to the missing try builder.
Error from importer:
ERROR: Failed to schedule builds for some bots:
  builder not found: "mac12-wpt-content-shell-fyi-rel"

Change-Id: Idc0e39b27bab311a4ca5fd44c2c5686da5bd10b7
Bug: 1385202, 1372969
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4171832
Commit-Queue: Weizhong Xia <weizhong@google.com>
Reviewed-by: Weizhong Xia <weizhong@google.com>
Cr-Commit-Position: refs/heads/main@{#1093208}
NOKEYCHECK=True
GitOrigin-RevId: d3707c6cec9d502ecbe26e01f4a8836fd7f1b4a3