libstdc++: do not pass a unique_ptr directly to stream insertion operator in CrossThreadMediaSourceAttachment.
Fix build error using libstdc++:
../../third_party/blink/renderer/modules/mediasource/cross_thread_media_source_attachment.cc:578:37: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::unique_ptr<blink::WebMediaSource>’)
  578 |            << ", web_media_source=" << web_media_source;
      |                                     ^~ ~~~~~~~~~~~~~~~~
      |                                        |
      |                                        std::unique_ptr<blink::WebMediaSource>

This is because libstdc++ does not provide an operator<< implementation for std::unique_ptr
(but libc++ does provide it).

Bug: 957519
Change-Id: I344b0f289d625b036e6bd4cafac1000cff6f23ac
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2486260
Reviewed-by: Matthew Wolenetz <wolenetz@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#819267}
GitOrigin-RevId: 00d00be99dd3de60cbf77ab99c05d602f0c40846