[compile hints] Fix deps around blink core
The buildflag header added recently in blink/renderer/bindings takes
part in some less obvious parts of the build, deps-wise, and made it
so several compiles could flake in a clean build, such as:
obj/third_party/blink/renderer/core/core_hot/document.o
obj/third_party/blink/renderer/core/animation/animation/animation_timeline.o
obj/third_party/blink/renderer/core/exported/exported/web_document.o
(and more from core/core_hot, core/animation, core/exported).

In the core_hot example, the error looks like this:
In file included from ../../third_party/blink/renderer/core/dom/document.cc:129:
In file included from ../../third_party/blink/renderer/core/dom/context_features.h:32:
In file included from ../../third_party/blink/renderer/core/page/page.h:44:
../../third_party/blink/renderer/bindings/core/v8/v8_compile_hints.h:8:10:
fatal error: 'third_party/blink/renderer/bindings/buildflags.h' file not found

Fix by (1) adding the dep in core_generated, which most relevant targets
already depend on, and (2) adding the dep separately in core_hot,
because that doesn't use core_generated and I'm not sure if it should,
since it already reproduces other necessary deps directly.

Bug: chromium:1406506
Change-Id: I32fae863b3b207356c8914aa7abec7346b9b72c3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4421956
Reviewed-by: Kouhei Ueno <kouhei@chromium.org>
Commit-Queue: Tomasz Śniatowski <tsniatowski@vewd.com>
Reviewed-by: Marja Hölttä <marja@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1132963}
NOKEYCHECK=True
GitOrigin-RevId: c124749bad671af4ea38fb8c1f9865a1edddb31d