Revert "VT: Fix snapshot rect for a resizing virtual keyboard"
This reverts commit 39a9955f80b8d589e0e89cb37d34250a9a642f87.

Reason for revert: Added tests are consistently failing on multiple builders, e.g.
https://ci.chromium.org/ui/p/chrome/builders/ci/android-arm64-tests/9426/overview
https://ci.chromium.org/ui/p/chromium/builders/ci/android-pie-x86-rel/11333/overview

with message
java.lang.NoSuchMethodError: No virtual method inset(IIII)V in class Landroid/graphics/Rect; or its super classes (declaration of 'android.graphics.Rect' appears in /system/framework/framework.jar)

Original change's description:
> VT: Fix snapshot rect for a resizing virtual keyboard
>
> ViewTransitions compute the "snapshot rect" which is a viewport-like
> rect that doesn't change size when UI such as scrollbars, virtual
> keyboard, mobile URL bar are showing or hidden.
>
> When the keyboard is in a resize-content mode (so that innerHeight is
> changed by the keyboard, see:
> https://developer.chrome.com/blog/viewport-resize-behavior/), the
> snapshot rect must account for the keyboard by outsetting the layout
> viewport.
>
> This CL plumbs the virtual-keyboard height into the renderer via
> SynchronizeVisualProperties so that DocumentTransitionStyleTracker can
> use this value to perform the outset. This value includes any keyboard
> accessories such as the autofill bar.
>
> Since the keyboard resize behavior is implemented in the //chrome layer,
> this CL adds end-to-end chrome browser tests for this behavior. This
> requires introducing some hand-rolled pixel testing functionality into
> java tests which isn't common so also requires plumbing the
> InsertVisualStateCallback mechanism into java, allowing tests to wait on
> a Blink main frame to be presented to the screen.
>
> Bug: 1350910
> Change-Id: Ie1b01cb5082e7059a0e03b99d25a361f3f87e189
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3971061
> Commit-Queue: David Bokan <bokan@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: danakj <danakj@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1069581}

Bug: 1350910
Change-Id: Ief19d82f8c69288d3ad2109b5590305b173f34c3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4021524
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Patrick Noland <pnoland@chromium.org>
Owners-Override: Patrick Noland <pnoland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1069838}
NOKEYCHECK=True
GitOrigin-RevId: 026eae0754d869b4258c1d950b73947533888c0b