Landing Recent QUIC changes until 019/01/25 10:48:28
There are no flags to be updated.

--------------------------------------------------
Date:   Fri Jan 25 19:26:18 2019 +0000

Change SerializeHeadersFrameHeader() to take header frame length.

n/a (No functional change.)

Change SerializeHeadersFrameHeader() to take header frame payload length
instead of entire header frame payload, just like
SerializeDataFrameHeaders() already takes a length.  Also change
SerializeDataFrameHeaders() argument name from |length| to
|payload_length| for clarity.

Motivation:  Just like SerializeDataFrameHeaders(),
SerializeHeadersFrameHeader() does not need to know the entire frame
payload, only its length.  This is in contrast with Serialize*Frame()
methods that serialize the payload in addition to the frame header.

Merge internal change: 230937339

https://chromium-review.googlesource.com/c/1454132/


--------------------------------------------------
Date:   Fri Jan 25 22:34:31 2019 +0000

Set is_current_packet_connectivity_probing_ to false in the end of
QuicConnection::ProcessUdpPacket. Protected by default true flag
FLAGS_quic_reloadable_flag_quic_clear_probing_mark_after_packet_processing.

This should fix the flaky test in b/122963316, see
http://b/122963316#comment3 for more details.

Merge internal change: 230970486

https://chromium-review.googlesource.com/c/1454134/

Bug: 122963316

--------------------------------------------------
Date:   Sat Jan 26 12:14:43 2019 +0000

In QUIC, accept packet number 0 in v99. Protected by version 99 and
gfe2_restart_flag_quic_uint64max_uninitialized_pn.

Merge internal change: 231039835

https://chromium-review.googlesource.com/c/1455016/

Bug: 121265775

--------------------------------------------------
Date:   Sun Jan 27 01:47:29 2019 +0000

Progress towards allowing variable length connection IDs

This CL refactors some of the QUIC codebase to plumb the version to
more places. It uses that to introduce
QuicUtils::CreateZeroConnectionId which currently provides 64bits set
to zero but will eventually allow clients like quartc to use
zero-length connection IDs.

refactoring, no change of behavior, not flag protected

NO_BUG=n/a

Merge internal change: 231077921

https://chromium-review.googlesource.com/c/1455019/


--------------------------------------------------
Date:   Mon Jan 28 19:13:29 2019 +0000

(n/a) Change QUIC_LOG_ to function-like macros, these
macros are allowed to 'return' different values based on the current
QUIC logging threshold. No bahavior change, not protected.

Merge internal change: 231254026

https://chromium-review.googlesource.com/c/1455058/


--------------------------------------------------
Date:   Mon Jan 28 19:57:32 2019 +0000

Change frame type values for IETF QUIC

This CL changes the frame type values used for IETF QUIC.

In doing this, a bug was found in the test code to test the
construction of IETF QUIC BLOCKED frames. This error was fixed. After
the test was corrected, there were no bugs in the core QUIC code.

There are no other logical or functional changes.

N/A all code is for version99/IETF QUIC only and is flag protected.fayang

Merge internal change: 231263146

https://chromium-review.googlesource.com/c/1455059/


--------------------------------------------------
Date:   Tue Jan 29 19:14:31 2019 +0000

Add QUIC v47 which will use IETF draft-17 header format with
demultiplexing bit. Protected by BLOCKED
FLAGS_quic_reloadable_flag_quic_enable_version_47.

Merge internal change: 231437303

https://chromium-review.googlesource.com/c/1455296/

Bug: 118781128

--------------------------------------------------
Date:   Wed Jan 30 00:48:40 2019 +0000

Do not include "base/logging.h" to silent BUILD error because of
./base/internal/logging.h:347:32: error: comparison of integers of
different signs: 'const int' and 'const unsigned long'
[-Werror,-Wsign-compare]

n/a (include only change)

Merge internal change: 231499804

https://chromium-review.googlesource.com/c/1455298/


--------------------------------------------------
Date:   Wed Jan 30 15:40:40 2019 +0000

Actually use IETF draft-17 header format with demultiplexing bit in
v47. Protected by BLOCKED
FLAGS_quic_reloadable_flag_quic_enable_version_47.

Merge internal change: 231592167

https://chromium-review.googlesource.com/c/1455300/

Bug: 118781128

--------------------------------------------------
Date:   Wed Jan 30 16:03:14 2019 +0000

Enable quic version 47 for Quartc.

Quic version 47 adds draft 17 bit, which will allow for demuxing quic
from RTP.

n/a (Quartc only)

Merge internal change: 231595566

https://chromium-review.googlesource.com/c/1455301/


--------------------------------------------------
Date:   Wed Jan 30 16:06:50 2019 +0000

In QUIC, change ParsedQuicVersion(PROTOCOL_UNSUPPORTED,
QUIC_VERSION_UNSUPPORTED) to UnsupportedQuicVersion().

(n/a) Refactor only, not protected.

Merge internal change: 231596249

https://chromium-review.googlesource.com/c/1455303/


--------------------------------------------------
Date:   Wed Jan 30 21:01:47 2019 +0000

remove unused #include base/macros.h in platform api.

Merge internal change: 231652158

https://chromium-review.googlesource.com/c/1455066/


--------------------------------------------------
Date:   Thu Jan 31 15:00:32 2019 +0000

n/a (No functional change in tests only.)

Introduce and use IsVersion99() method in QuicSpdySessionTestBase,
QuicSpdyStreamTest, and QuicSimpleServerSessionTest, where long inline
comparisons were used before, and in QuicSimpleServerStreamTest, where
there was a bool member before.

This simplifies a lot of conditionals in these tests.  This is
particularily beneficial as cr/231494986 is about to add even more.

Merge internal change: 231779345

https://chromium-review.googlesource.com/c/1455071/


--------------------------------------------------
Date:   Thu Jan 31 15:15:32 2019 +0000

n/a (Test only change, no functional change.)

Remove some redundant Times() expectations in three test files that will be
touched by a future CL cr/231494986.

Only remove redundant Times(1) and Times(AnyNumber) expectation is
there is also a WillOnce() or WillRepeatedly() expectation, which
implies the Times() expectation according to
https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#setting-expectations.
This is true regardless of whether the mock is a StrictMock or not.

Also change a Times(1).WillRepeatedly() to WillOnce().

Do not touch any Times(1) or Times(0) expectations if there are no WillOnce() or
WillRepeatedly(), because these are there to guide the reader.  (Even though
Times(1) is implied, and an expectation with Times(0) could be entirely removed
on a StrictMock.)

Merge internal change: 231781155

https://chromium-review.googlesource.com/c/1455072/


--------------------------------------------------
Date:   Thu Jan 31 15:17:58 2019 +0000

In QUIC, let v46 adopt QUIC bit header change, while v47 will be used
for CRYPTO frame change. Protected by BLOCKED
FLAGS_quic_reloadable_flag_quic_enable_version_46 and
FLAGS_quic_reloadable_flag_quic_enable_version_47.

Merge internal change: 231781497

https://chromium-review.googlesource.com/c/1455088/

Bug: 118781128

--------------------------------------------------
Date:   Thu Jan 31 15:48:32 2019 +0000

Only enable version 46 for Quartc, as v46 supports QUIC bit header now.

n/a (Quartc only)

Merge internal change: 231785372

https://chromium-review.googlesource.com/c/1455313/


--------------------------------------------------
Date:   Thu Jan 31 17:28:16 2019 +0000

Add QpackEncoder and QpackDecoder to QuicSpdySession only when using
QUIC version 99.  Not flag protected.

Merge internal change: 231799718

https://chromium-review.googlesource.com/c/1456278/


--------------------------------------------------
Date:   Thu Jan 31 21:13:58 2019 +0000

Use GetInvalidStreamId() instead of hard-coded 0s

In several places, the IETF-QUIC/Version99 code used hard coded 0s
to indicate an invalid stream id. This is incorrect. The 0s have
been replaced with QuicUtils::GetInvalidStreamId() calls so that
the correct invalid value is used.

N/A, all code is version 99/IETF-QUIC and thereby flag protected.

Merge internal change: 231839770

https://chromium-review.googlesource.com/c/1456279/


--------------------------------------------------
Date:   Fri Feb 1 17:24:43 2019 +0000

Pass the current connection to QuartcPacketWriter through PerPacketOptions.

This is mostly a nicer way to organize the relationship between the connection
and packet writer.  Under the previous arrangement, the connection registered
itself once with the packet writer and the packet writer assumed that it's only
used by that connection forevermore.

Under the new arrangement, the connection identifies itself whenever it sends a
packet.  Packets that are not sent by the connection will not cause confusion.

For example, the QuicDispatcher may send packets before a connection is created
(for version negotiation) or after it closes (rejecting the same connection id
for some time before allowing it to be reused).  Under the previous arrangement,
such packets could cause problems--there might still be a dead connection
registered with the packet writer.

This makes the QuartcPacketWriter usable with multiple connections.  Quartc
doesn't really need this (yet), but it's a nice benefit of organizing the code
this way.

n/a (Quartc only)

FIG_CHANGESET=011d79c4fbb12d50a6039d41a2fbad81f03c42be

Merge internal change: 231983473

https://chromium-review.googlesource.com/c/1456280/

Bug: 117157454

--------------------------------------------------
Date:   Sat Feb 2 00:08:37 2019 +0000

Deprecate FLAGS_quic_reloadable_flag_quic_limit_version_negotiation.

Also add a unit tests for doing version negotiation with a full size packet.

Merge internal change: 232055257

https://chromium-review.googlesource.com/c/1456281/

R=rch@chromium.org

Change-Id: If05c598e85bffe7933e5d404527a2acc358bcc59
Reviewed-on: https://chromium-review.googlesource.com/c/1456979
Reviewed-by: Ryan Hamilton <rch@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Reviewed-by: Bryan McQuade <bmcquade@chromium.org>
Commit-Queue: Ryan Hamilton <rch@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#629997}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 5bc8f59cee7889fb6908be526763bbb0b18be658