libstdc++ usage of std::floorf in NG out of flow layout part breaks libstdc++ build.
Use math.h floorf instead of std::floorf, as latter is not available in libstdc++
library.

Fixes this build error:
../../third_party/blink/renderer/core/layout/ng/ng_out_of_flow_layout_part.cc: In member function ‘void blink::NGOutOfFlowLayoutPart::ComputeStartFragmentIndexAndRelativeOffset(const blink::NGOutOfFlowLayoutPart::ContainingBlockInfo&, blink::WritingMode, WTF::wtf_size_t*,
 blink::LogicalOffset*) const’:
../../third_party/blink/renderer/core/layout/ng/ng_out_of_flow_layout_part.cc:1194:16: error: ‘floorf’ is not a member of ‘std’; did you mean ‘floor’?
 1194 |       int(std::floorf(remaining_block_offset / fragmentainer_block_size));
      |                ^~~~~~
      |                floor

Bug: 957519
Change-Id: I7d8f78c04948a6c0e37cbca59bdbca485fc839d3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2394165
Commit-Queue: Ian Kilpatrick <ikilpatrick@chromium.org>
Reviewed-by: Ian Kilpatrick <ikilpatrick@chromium.org>
Cr-Commit-Position: refs/heads/master@{#804612}
GitOrigin-RevId: 63233f8c171380997d5fe51430e54ce101a918d8