CallSetupStateTrackerTest: Fix template handling in member functions
This fixes the build with GCC, which was complaining with error messages
such as:

    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker_unittest.cc:60:13: error: explicit specialization in non-namespace scope ‘class blink::CallSetupStateTrackerTest’
       template <>
                 ^
    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker_unittest.cc:65:13: error: explicit specialization in non-namespace scope ‘class blink::CallSetupStateTrackerTest’
       template <>
                 ^
    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker_unittest.cc:66:17: error: ‘blink::AnswererState blink::CallSetupStateTrackerTest::current_state() const’ cannot be overloaded with ‘blink::OffererState blink::CallSetupStateTrackerTest::current_state() const’
       AnswererState current_state() const {
                     ^~~~~~~~~~~~~
    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker_unittest.cc:61:16: note: previous declaration ‘blink::OffererState blink::CallSetupStateTrackerTest::current_state() const’
       OffererState current_state() const {
                    ^~~~~~~~~~~~~

For current_state(), move the template specializations outside of
CallSetupStateTrackerTest. Having them in CallSetupStateTrackerTest
officially requires C++17 (specifically, C++ DR727). While clang has
implemented DR727 for other -std= options, GCC is stricter and only builds
that code in C++17 mode.

For NoteStateEvent, drop the template bits altogether: the two
NoteStateEvent() functions work as regular overloads and do not need any
templates.

Bug: 819294
Change-Id: I3f839d9a70670de1f52db14efcbd10b3a199b84e
Reviewed-on: https://chromium-review.googlesource.com/c/1352256
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#611666}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 707771a033e3e99edb0e2cb35f860761968b9dc2