bindings: Use str.strip() instead of string.strip()
string.strip() has been removed in Python 3.
Use str.strip() instead, which exists on both Python 2 and 3 and does the same thing.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 109, in <module>
    sys.exit(main())
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 101, in main
    interface_name_global_names.update(
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 82, in idl_files_to_interface_name_global_names
    global_names = idl_file_to_global_names(idl_filename)
  File "../../third_party/blink/renderer/bindings/scripts/compute_global_objects.py", line 63, in idl_file_to_global_names
    extended_attributes = get_interface_extended_attributes_from_idl(
  File "C:\Google\chromium\src\third_party\blink\renderer\bindings\scripts\utilities.py", line 440, in get_interface_extended_attributes_from_idl
    name, _, value = map(string.strip, concatenated.partition('='))
AttributeError: module 'string' has no attribute 'strip'

Bug: 941669
Change-Id: I716bbcfa691d24d2d9268d02dd9772275e2cd199
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124569
Commit-Queue: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#754302}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 49ceb4ddb94c23f4d16239b8dfaa1cce673e6412