GCC: rename Color getter to LineColor in TextDecorationInfo to avoid clashing with Color type
GCC fails to compile the Color getter in TextDecorationInfo, as it
gets confused by different declarations in different namespaces:
../../third_party/blink/renderer/core/paint/text_decoration_info.h: At global scope:
../../third_party/blink/renderer/core/paint/text_decoration_info.h:76:9: error: declaration of ‘blink::Color blink::TextDecorationInfo::Color() const’ changes meaning of ‘Color’ [-fpermissive]
   76 |   Color Color() const;
      |         ^~~~~

To avoid that, we rename the getter to be LineColor.

Bug: 819294
Change-Id: I5b1a0d8a9c4580029ba8148281f9a3a514a88b62
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2339487
Commit-Queue: Stephen Chenney <schenney@chromium.org>
Reviewed-by: Stephen Chenney <schenney@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#795934}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e720ea2149308ace1fd1a7a0e5ec27bc3ac31372